name: Build SignumJS

on:
  push:
    branches:
      - "**"
    paths:
      - "lib/**"
    tags-ignore:
        - desktop-[0-9]+.[0-9]+.[0-9]+*

jobs:
  build-burstjs:
    name: Test and Build BurstJS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run BurstJS Tests
        run: |
          npm ci
          npm t

      - name: Build/Bundle SignumJS
        run: npm run build

      - name: Build Angular Web App
        run: |
          cd ../web/angular-wallet
          npm ci
          npm run build:ci


